name = "Builder Pablito 2"
author = "P4tit0"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60d770ed8607a80fcfbdc841e6af7a4a9ed9fb8f8c8ec5be7a045a83ecc9bef6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
