name = "Builder Pablito 2"
author = "P4tit0"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71ef8de4dba4dbc55153e5f2632e9c544ebdc96382a5052e6f3bd24daa1eeab3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
