name = "Builder Pablito 2"
author = "P4tit0"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7683a28f3de08746fbaadf5285272c62c58bb761545e98ec2dad81094f2506b0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
